### ISSUE TITLE
Updates to bluprint

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/bluprint_github-action-scraper#5]
- Add `env` based publish location (local or server)
- Add `publishCSV` script to publish CSV to the server
- Format `index.js` into three discrete steps for ease of use
- Add a global variable for the `server path` based on the project name slug
- Prepend `actions_` to project name when creating the GitHub repository
- Add single function to fetch and return data that works for both `csv/json` files 
- Add status alerts via `webhooks` at each step @hobbes7878

**Comment by hobbes7878** [comment]
Logging added in.

One question: Do you want to keep the files you write to the temp directory locally in `data/`? Maybe you do! Otherwise, can add to the gitignore, too.

**Comment by pkd2512** [comment]
Yea, I find that convenient, just to save a snapshot of my local workflow. Besides, the way the local filesave is written now, assumes there is a data folder, else will crap out. Which is why, I had to add that `.keep` file when it starts fresh off the blueprint. But can rethink this bit, if having a local data folder sounds confusing or there is a more elegant way to handling it.
